# Generated by Django 5.0 on 2023-12-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена услуги')),
            ],
        ),
    ]
