# Generated by Django 5.0 on 2023-12-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='date',
        ),
    ]
