# Generated by Django 5.0 on 2023-12-30 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
